---
- hosts: ios
  gather_facts: no
  connection: network_cli

  tasks:

  - name: CREATE NEW BANNER ON {{ ansible_ssh_host }}
    ios_config:
      lines:
        - banner motd ^Welcome to the 2 day CCNA boot camp^

  - name: SHOW RUN | BEG BANNER ON {{ ansible_ssh_host }}
    ios_command:
      commands:
        - show run | beg banner
    register: banner

  - debug: var=banner.stdout_lines
