---

- hosts: ios
  remote_user: pi
  become: yes
  become_method: enable
  connection: network_cli

  tasks:
  - name: SHOW RUN | BEG BANNER
    ios_command:
      authorize: yes
      commands:
        - show run | beg banner
    register: banner

  - debug: var=banner.stdout_lines

  - name: CREATE NEW BANNER
    ios_config:
      authorize: yes
      lines:
        - banner motd ^Welcome to the 2 day CCNA boot camp^

  - name: SHOW RUN | BEG BANNER
    ios_command:
      authorize: yes
      commands:
        - show run | beg banner
    register: banner

  - debug: var=banner.stdout_lines
