---
- hosts: ios
  gather_facts: no
  connection: network_cli

  tasks:

  - name: CONFIGURE BANNER ON {{ ansible_ssh_host }}
    ios_banner:
      banner: login
      text: "{{ lookup('file', './vars/raw_banner.cfg') }}"
      state: present

  - name: SHOW RUN | BEG BANNER ON {{ ansible_ssh_host }}
    ios_command:
      commands:
        - show run | beg banner
    register: banner

  - debug: var=banner.stdout_lines
