---
- hosts: ios
  gather_facts: no
  connection: network_cli

  tasks:

  - name: CONFIGURE BANNER ON CISCO DEVICES
    ios_banner:
      banner: login
      text: "{{ lookup('file', './vars/raw_banner.cfg') }}"
      state: present

  - name: SHOW RUN | SEC BANNER 
    ios_command:
      commands:
        - show run | sec banner
    register: banner

  - debug: var=banner.stdout_lines
