---

- hosts: ios
  become: yes
  connection: network_cli

  tasks:
  - name: CONFIGURE SSH VERSION 2 ON {{ ansible_hostname }}
    ios_config:
      lines:
        - ip ssh version 2

  - name: SHOW RUN | I SSH ON {{ ansible_hostname }}
    ios_command:
      commands:
        - show run | i ssh
    register: after_v2

  - debug: var=after_v2.stdout_lines

