---
- name: ios
  hosts: all
  gather_facts: no
  connection: network_cli


  tasks:
 
  - name: SET COMMUNITY STRING 
    ios_config:
      lines:
        - snmp-server community thenetwork.engineer

  - name: TRAP-SOURCE LOOPBACK0 
    ios_config:
      lines:
         - int lo0
         - snmp-server trap-source Loopback0

  - name: SET CONTACT INFO 
    ios_config:
      lines:
        - snmp-server contact colin@thenetwork.engineer

  - name: ENABLE TRAPS ON {{ ansible_host }}
    ios_config:
      lines:
        - snmp-server enable traps ospf state-change
        - snmp-server enable traps ospf errors
        - snmp-server enable traps ospf retransmit
        - snmp-server enable traps ospf lsa
        - snmp-server enable traps ospf cisco-specific errors
        - snmp-server enable traps ospf cisco-specific retransmit
        - snmp-server enable traps ospf cisco-specific lsa


  - name: SET SNMP SERVER ADDRESS 
    ios_config:
      lines:
        - snmp-server host 192.168.161.25 pwdhere




