---
-   hosts: localhost
    gather_facts: yes

    vars:
     switch_list:
      - 10.22.22.1
      - 10.22.22.2
      - 10.22.22.3
      - 10.22.22.4
      - 10.22.22.5
      - 10.22.22.6
      - 10.22.22.69

    tasks:

    - name: get_PortSummary_from_ALL_devices_from_PRIME
      uri:
        url: https://10.23.77.200/webacs/api/v4/op/statisticsService/device/portSummary.json?ipAddress={{ item }}
        validate_certs: no
        method: GET
        return_content: yes
        headers:
            Content-Type: "application/json"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      with_items: "{{switch_list}}"
      register: Port_Summary

#    - name: Show Collected Data
#      debug:
#            var: Port_Summary.results

    - name: set db fields to stored 
      uri:
        url: 'http://10.23.77.202:9200/portstatus-{{ansible_date_time.date}}'
        method: PUT
        return_content: yes
        body_format: json
        body: '{
                "mappings": {
                    "switch": {
                        "properties": {
                                "deviceIP" : {
                                    "type": "text",
                                    "store" : true    
                                },
                                "Up Ports" : {
                                    "type": "long",
                                    "store" : true
                                },
                                "Operationally Down Ports" : {
                                    "type": "long",
                                    "store" : true
                                },
                                "Administratively Down Ports" : {
                                    "type": "long",
                                    "store" : true
                                },
                                "Datetime" : {
                                    "type": "date",
                                    "store" : true
                                },
                                "Myindex" : {
                                    "type": "long",
                                    "store" : true
                                }
                        }
                    }
                }
               }'
        headers:
            Content-Type: "application/json"
        status_code: [201, 200, 400]

    - name: save output to elastic
      uri:
        url: 'http://10.23.77.202:9200/portstatus-{{ansible_date_time.date}}/switch/'
        method: POST
        return_content: yes
        body_format: json
        body: '{
                "deviceIP":"{{item._ansible_item_label}}",
                "Up Ports":"{{item.json.mgmtResponse.statisticsDTO.0.childStatistics.childStatistic.0.statisticEntries.statisticEntry.0.entryValue}}",
                "Operationally Down Ports":"{{item.json.mgmtResponse.statisticsDTO[0].childStatistics.childStatistic[1].statisticEntries.statisticEntry[0].entryValue}}",
                "Administratively Down Ports":"{{item.json.mgmtResponse.statisticsDTO[0].childStatistics.childStatistic[2].statisticEntries.statisticEntry[0].entryValue}}",
                "@timestamp":"{{ansible_date_time.iso8601}}",
                "Datetime":"{{ansible_date_time.iso8601}}",
                "Myindex":"{{ 1000000 | random }}"
                }'
        headers:
            Content-Type: "application/json"
        status_code: 201
      register: elastic_result
      with_items: "{{Port_Summary.results}}"

