---
-   hosts: localhost
    gather_facts: no

    tasks:

    - name: get_device_IDs_from_PRIME_in_JSON
      uri:
        url: https://10.23.77.200/webacs/api/v4/data/InventoryDetails.json?
        validate_certs: no
        method: GET
        return_content: yes
        headers:
            Content-Type: "application/json"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      register: prime_devices

#    - debug:
#        var: prime_devices.content

    - name: parse the JSON output from CPI and save it in a new dictionary
      set_fact: 
         prime_devices_json: "{{prime_devices.content | from_json }}"

#    - debug:
#        msg: "{{prime_devices_json}}"

#    - name: Get index of last device
#      set_fact:
#        Num_Of_Devices: "{{prime_devices_json['queryResponse']['@last']}}"

    - name: Create Array of entityIDs - one for each device
      set_fact:
        prime_device_IDs: "{{prime_device_IDs| default([]) + [item] }}"
      with_items: "{{prime_devices_json['queryResponse']['entityId'] | list}}"
    
    - debug:
            var: prime_device_IDs

#    - name: Let's get one URL
#      set_fact:
#        1st_Device_URL: "{{prime_device_IDs[0]['@url']}}"
#
#    - debug:
#            var: 1st_Device_URL

    - name: Create list Device URLs
      set_fact:
        Device_URLS: "{{Device_URLS| default([]) + [item] }}"
      with_items: "{{prime_device_IDs|json_query('[*].\"@url\"')}}"

    - debug:
            var: Device_URLS
#    https://stackoverflow.com/questions/37748174/extract-last-character-of-string-with-ansible-and-regex-replace-filter
#    https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html

    - name: get_facts_from_1stdevice_from_PRIME
      uri:
        url: "{{ prime_device_IDs[0]['@url'] }}"
        validate_certs: no
        method: GET
        return_content: yes
        headers:
            Content-Type: "application/json"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      register: 1stdevice_facts_json

    - name: Show 1st device facts
      debug:
        var: 1stdevice_facts_json.content

    - name: get_facts_from_ALL_devices_from_PRIME
      uri:
        url: "{{ item }}"
        validate_certs: no
        method: GET
        return_content: yes
        headers:
            Content-Type: "application/json"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      register: device_facts_json
      with_items: "{{Device_URLS}}"

    - name: Show ALL device facts
      debug:
        var: device_facts_json.content

#    - name: Create Array of only URLs - one for each device
#      set_fact:
#        prime_device_only_urls: "at array position {{ item.0 }} there is a value {{ item.1 }}, we want {{ item.1 }}[{{item.0}}] "
#      with_indexed_items: "{{prime_device_IDs}}"
#
#    - debug:
#        var: prime_device_only_urls
                                     
#      
#    - name: get_switch_IPaddress
#         switch_IP: "{{switch_IPaddress.matches.0.address}}"
#         switch_Interface: "{{switch_If.matches.0.clientInterface}}"
#         switch_hostname: "{{switch_name.matches.0.deviceName}}"
#
