---
-   hosts: localhost
    gather_facts: no

    vars:
     switch_list:
      - 10.22.22.1
      - 10.22.22.2
      - 10.22.22.3
      - 10.22.22.4
      - 10.22.22.5

    tasks:

    - name: get_PortSummary_from_ALL_devices_from_PRIME
      uri:
        url: https://10.23.77.200/webacs/api/v4/op/statisticsService/device/portSummary.json?ipAddress={{ item }}
        validate_certs: no
        method: GET
        return_content: yes
        headers:
            Content-Type: "application/json"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      with_items: "{{switch_list}}"
      register: device_facts

    - name: Show Collected Data
      debug:
            var: device_facts.results


#    - name: parse the JSON output from CPI and save it in a new dictionary
#      set_fact: 
#         All_Port_Status_json: "{{ device_facts.results[0].json }}"

#    - debug:
#        msg: "{{All_Port_Status_json}}"

    - name: Get specific Values from JSON
      set_fact:
        First_Switch_Up_Ports: json_query('device_facts.results[0].json.mgmtResponse.statisticsDTO[0].childStatistics.childStatistic[0].statisticEntries.statisticEntry[0].entryValue')

    - debug:
            var: First_Switch_Up_Ports


#    - name: save output to elastic
#      uri:
#        url: 'http://10.23.77.202:9200/portstatus-{{ansible_date_time.date}}/switch/'
#        method: POST
#        return_content: yes
#        body_format: json
#        body: '{
#                "deviceName":"{{item.statisticEntries.statisticEntry.5.entryValue}}",
#                "deviceIP":"{{item.statisticEntries.statisticEntry.6.entryValue}}",
#                "averageCPU":"{{item.statisticEntries.statisticEntry.4.entryValue}}",
#                "maxCPU":"{{item.statisticEntries.statisticEntry.3.entryValue}}",
#                "minCPU":"{{item.statisticEntries.statisticEntry.2.entryValue}}",
#                "currentCPU":"{{item.statisticEntries.statisticEntry.1.entryValue}}",
#                "@timestamp":"{{ansible_date_time.iso8601}}",
#                "Datetime":"{{ansible_date_time.iso8601}}",
#                "Myindex":"{{ 1000000 | random }}"
#                }'
#        headers:
#            Content-Type: "application/json"
#        status_code: 201
#      register: elastic_result
#      with_items: "{{All_Port_Status_json.mgmtResponse.statisticsDTO}}"

