---
-   hosts: localhost
    gather_facts: no

    tasks:

    - name: get_device_IDs_from_PRIME_in_JSON
      uri:
        url: https://10.23.77.200/webacs/api/v4/data/InventoryDetails.json?
        validate_certs: no
        method: GET
        return_content: yes
        headers:
            Content-Type: "application/json"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      register: prime_devices

#    - debug:
#        var: prime_devices.content

    - name: parse the JSON output from CPI and save it in a new dictionary
      set_fact: 
         prime_devices_json: "{{prime_devices.content | from_json }}"

#    - debug:
#        msg: "{{prime_devices_json}}"

#    - name: Get index of last device
#      set_fact:
#        Num_Of_Devices: "{{prime_devices_json['queryResponse']['@last']}}"

    - name: Create Array of entityIDs - one for each device
      set_fact:
        prime_device_IDs: "{{prime_device_IDs| default([]) + [item] }}"
      with_items: "{{prime_devices_json['queryResponse']['entityId'] | list}}"
    
    - debug:
            var: prime_device_IDs

#    - name: Let's get one URL
#      set_fact:
#        First_Device_URL: "{{prime_device_IDs[0]['@url']}}"
#
#    - debug:
#            var: First_Device_URL

    - name: Create list Device URLs
      set_fact:
        Device_URLS: "{{Device_URLS| default([]) + [item] }}"
      with_items: "{{prime_device_IDs|json_query('[*].\"@url\"')}}"

#    - debug:
#            var: Device_URLS

    - name: get_facts_from_1stdevice_from_PRIME
      uri:
        url: "{{ prime_device_IDs[0]['@url'] }}.json"
        validate_certs: no
        method: GET
        return_content: yes
        headers:
            Content-Type: "application/json"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      register: FirstDevice_facts

    - name: Show 1st device facts
      debug:
            var: FirstDevice_facts.content

    - name: get_facts_from_ALL_devices_from_PRIME
      uri:
        url: "{{ item }}.json"
        validate_certs: no
        method: GET
        return_content: yes
        headers:
            Content-Type: "application/json"
        user: devnet
        password: Maticmind2018
        force_basic_auth: yes
      with_items: "{{Device_URLS}}"
      register: device_facts

    - name: Show ALL device facts
      debug:
            var: device_facts.results

#    - name: parse the JSON output from CPI and save it in a new dictionary
#      set_fact: 
#         device_facts_json: "{{device_facts.results | from_json }}"

    - name: Get specific Values from JSON
      set_fact:
        Device_IP: "{{Device_IP| default([]) + [item] }}"
      with_items: "{{
#                    device_facts.results|json_query('[*].json.queryResponse.entity[0].\"inventoryDetailsDTO\".\"summary\".\"deviceName\"'),
                    device_facts.results|json_query('[*].json.queryResponse.entity[0].\"inventoryDetailsDTO\".\"ethernetInterfaces\".\"ethernetInterface\".[*].\"operationalStatus\"')
                    }}"
#      when: json_query('device_facts.results.[*].json.queryResponse.entity[0]."inventoryDetailsDTO"."ethernetInterfaces"."ethernetInterface".[*]."operationalStatus"') == "DOWN"

    - debug:
            var: Device_IP

#    - name: Create list Device URLs
#      set_fact:
#        Device_URLS: "{{Device_URLS| default([]) + [item] }}"
#      with_items: "{{prime_device_IDs|json_query('[*].\"@url\"')}}"
#
#    - debug:
#            var: Device_URLS

#    - name: Create Array of only URLs - one for each device
#      set_fact:
#        prime_device_only_urls: "at array position {{ item.0 }} there is a value {{ item.1 }}, we want {{ item.1 }}[{{item.0}}] "
#      with_indexed_items: "{{prime_device_IDs}}"
#
#    - debug:
#        var: prime_device_only_urls
                                     
#      
#    - name: get_switch_IPaddress
#         switch_IP: "{{switch_IPaddress.matches.0.address}}"
#         switch_Interface: "{{switch_If.matches.0.clientInterface}}"
#         switch_hostname: "{{switch_name.matches.0.deviceName}}"
#
