---
- hosts: MM_Vimodrone
  gather_facts: no
  connection: network_cli

- name: Check that you can connect (GET) to CUCM and it returns a status 200
  uri:
    url: https://10.142.0.1:8443/axl/
    user: devnet
    password: devnet

# Check that a page returns a status 200 and fail if the word AXL is not
# in the page contents.

- name: Check if CUCM returns AXL in its content
  uri:
    url: https://10.142.0.1:8443/axl/
    user: devnet
    password: devnet
    return_content: yes
  register: page_content
  failed_when: "'AXL' not in page_content.content"

- name: Create a JIRA issue
  uri:
    url: https://10.142.0.1:8443/axl/
    method: POST
    user: your_username
    password: your_pass
    body: "{{ lookup('file','issue.json') }}"
    force_basic_auth: yes
    status_code: 201
    body_format: json

# Login to a form based webpage, then use the returned cookie to
# access the app in later tasks

- uri:
    url: https://your.form.based.auth.example.com/index.php
    method: POST
    body_format: form-urlencoded
    body:
      name: your_username
      password: your_password
      enter: Sign in
    status_code: 302
  register: login
           
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/10.5">
    <soapenv:Header/>
    <soapenv:Body>
        <ns:getPhone>
            <name>SEP000C29E85240</name>
        </ns:getPhone>
    </soapenv:Body>
</soapenv:Envelope>
