---
- hosts: MM_Vimodrone_DEVNET
  gather_facts: no
  connection: network_cli


  vars:
    ansible_network_os: ios
    
  tasks:

  - name: run multiple commands on switch DEVNET
    ios_command:
      commands:
        - configure terminal
        - interface GigabitEthernet1/0/2
        - power inline never
        - description {{username_mm}}
        - end
        - wr

#    when: username_mm == "fmenezes"

  - debug:
      msg: "The received username is {{ username_mm }} so PWR is removed"
    when: username_mm == "fmenezes"

  - debug:
      msg: "The received username is {{ username_mm }} so PWR is NOT removed"
    when: username_mm != "fmenezes"
  
