---
- hosts: MM_Vimodrone_DEVNET
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ios
    username_mm: 'fmenezes'
  
  tasks:

  - name: run multiple commands on switch DEVNET
    ios_command:
      commands:
        - configure terminal
        - interface GigabitEthernet1/0/2
        - description {{username_mm}}
        - end
        - wr
      
    when: username_mm == "fmenezes"
   
  - debug: 
      
