---
- hosts: MM_Vimodrone_DEVNET
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ios
    username: 4 
  
  tasks:

  - name: run multiple commands on switch DEVNET
    ios_command:
      commands:
        - configure terminal
        - interface GigabitEthernet1/0/2
        - no power inline never
        - end
        - wr
    when: 'username' == 4
  - debug: var=banner.stdout_lines
  
