-   hosts: MM_Vimodrone
    gather_facts: no
    connection: network_cli

    vars:
      ansible_network_os: ios

    tasks:

    - ios_command:
        provider:
            timeout: 30
        commands: copy running-config startup-config
#        commands: show ver

