---
- hosts: ios
  gather_facts: no
  connection: local

  tasks:

- name: "create a diff"
    napalm_install_config:
      hostname: "{{ inventory_hostname }}"
      username: "{{ creds['username'] }}"
      password: "{{ creds['password'] }}"
      dev_os: "ios"
      config_file: initial.conf
      commit_changes: false
      replace_config: false
      diff_file: initial.diff

