---
- hosts: MM_Vimodrone
  gather_facts: no
  connection: network_cli

  vars:
       ansible_network_os: ios

  tasks:

  - name: CLEAR BANNER ON CISCO DEVICES
    ios_banner:
      banner: login
      state: absent
